export default {
  APP: {
    ACCOUNT: {
      CREATE_BEGIN: '@@APP/USER/CREATE',
      CREATE_SUCCESS: '@@APP/USER/CREATE/SUCCESS',
      CREATE_FAIL: '@@APP/USER/CREATE?FAIL',
    },
    ATTEMPT_LOGIN: '@@APP/LOGIN/ATTEMPT',
    SUCCESS_LOGIN: '@@APP/LOGIN/SUCCESS',
    FAIL_LOGIN: '@@APP/LOGIN/FAIL',
    RESET_LOGIN: '@@APP/LOGIN/RESET',
    WRAPPER: {
      INIT: '@@APP/WRAPPER/INIT',
    },
  },
  DATA: {
    LOAD_DATA: '@@DATA/LOAD/START',
    DATA_COMPLETE: '@@DATA/LOAD/COMPLETE',
    DATA_ERROR: '@@DATA/LOAD/ERROR',
  },
  DOCTOR: {
    LOAD_DATA: '@@DOCTOR/LOAD/START',
    DATA_COMPLETE: '@@DOCTOR/LOAD/COMPLETE',
    DATA_ERROR: '@@DOCTOR/LOAD/ERROR',
    SELECT: '@@DOCTOR/SELECT',
    CLEAR: '@@DOCTOR/CLEAR',
  },
};
