export default {
  APP: {
    ATTEMPT_LOGIN: '@@APP/LOGIN/ATTEMPT',
    SUCCESS_LOGIN: '@@APP/LOGIN/SUCCESS',
    FAIL_LOGIN: '@@APP/LOGIN/FAIL',
    RESET_LOGIN: '@@APP/LOGIN/RESET',
  },
  DATA: {
    LOAD_DATA: '@@DATA/LOAD/START',
    DATA_COMPLETE: '@@DATA/LOAD/COMPLETE',
    DATA_ERROR: '@@DATA/LOAD/ERROR',
  },
};
